# Generated by Django 4.1.7 on 2023-02-27 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_venue', models.CharField(max_length=100)),
                ('event_pic', models.FileField(default='', upload_to='sports_app/pictures')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
