# Generated by Django 4.1.7 on 2023-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0002_contact_employee_feedback_rating_sport_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_plan',
            name='charge',
            field=models.IntegerField(),
        ),
    ]
