# Generated by Django 4.1.7 on 2023-03-15 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0003_alter_sport_plan_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=45)),
                ('student_email', models.EmailField(max_length=40)),
                ('student_password', models.CharField(max_length=20)),
                ('student_phone', models.IntegerField()),
                ('student_gender', models.CharField(max_length=10)),
                ('student_dob', models.DateField(default=django.utils.timezone.now)),
                ('student_pic', models.FileField(default='', upload_to='sports_app/student')),
                ('student_address', models.TextField()),
                ('parent_name', models.CharField(max_length=45)),
                ('padent_phone', models.IntegerField()),
            ],
        ),
    ]
