# Generated by Django 4.1.7 on 2023-03-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0005_alter_student_padent_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='padent_phone',
            new_name='parent_phone',
        ),
    ]
