# Generated by Django 4.1.7 on 2023-03-21 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_rename_padent_phone_student_parent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.CharField(default=None, max_length=40)),
                ('sender_id', models.CharField(default=None, max_length=40)),
                ('msg_subject', models.CharField(default=None, max_length=40)),
                ('msg_content', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receiver_status', models.BooleanField(default=True, null=True)),
                ('sender_status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
