# Generated by Django 4.1.7 on 2023-03-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0008_student_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=None, max_length=40)),
                ('coach_id', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
