# Generated by Django 4.1.7 on 2023-04-14 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0010_sport_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('email', models.CharField(default=None, max_length=40)),
                ('phone', models.CharField(default=None, max_length=40)),
                ('gender', models.CharField(default=None, max_length=40)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('height', models.CharField(default=None, max_length=40)),
                ('weight', models.CharField(default=None, max_length=40)),
                ('health', models.CharField(default=None, max_length=40)),
                ('prefered_sport', models.CharField(default=None, max_length=40)),
                ('parent_name', models.CharField(default=None, max_length=40)),
                ('parent_phone', models.CharField(default=None, max_length=40)),
                ('address', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
