# Generated by Django 4.2.2 on 2023-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_app", "0013_employee_facebook_employee_instagram_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="event_date", new_name="date",
        ),
        migrations.RenameField(
            model_name="event", old_name="event_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="event", old_name="event_venue", new_name="venue",
        ),
        migrations.RemoveField(model_name="event", name="event_description",),
        migrations.RemoveField(model_name="event", name="event_pic",),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default="NA"),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="event",
            name="sports",
            field=models.CharField(default="2023-06-07", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="team1",
            field=models.CharField(default="NA", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="team2",
            field=models.CharField(default="NA", max_length=50),
            preserve_default=False,
        ),
    ]
