# Generated by Django 4.2.2 on 2023-06-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_app", "0014_rename_event_date_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.CharField(default="NA", max_length=10),
        ),
    ]
